version: '3'
services:
  orientdb3:
    image: orientdb:3.0.4
    
    environment:
      ORIENTDB_ROOT_PASSWORD: sosote16
      ORIENTDB_NODE_NAME: "odb1"
      ORIENTDB_OPTS_MEMORY: "-Xms512m -Xmx1G"    
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.7"
          memory: 1024M
      restart_policy:
        condition: on-failure
    ports:
      - 2480:2480
      - 2424:2424
    networks:
    - webnet
    logging:
      driver: json-file
      options:``
        max-size: "200k"
        max-file: "10"
    
    networks:
      webnet: